#!/usr/bin/perl -w
use strict;
require 'lowlib.pl';

my ($remote_login, $remote_ip, $matched_hostname, $title)	= ();
my $search	= shift;
unless ($search) { exit(); }
if ( $search	=~ m/^(\w+)\@(.+)/ )	{ $remote_login = $1; $search = $2; }
my %hosts	= ();
my @hosts	= read_file('/etc/hosts');

LINE:	foreach my $line (@hosts)
{
	$line	=~	s/#.*$//g;
	if ($line	=~ m/^\s*$/)	{ next LINE; }
	if ($line	=~ m/^\s*((?:\d{1,3}\.){3}\d{1,3})\s+(.+)/ )
	{
		my $ip_address	= $1;
		my @aliases	= split(/\s+/, $2);
		foreach my $alias (@aliases)
			{ $hosts{$alias}	= $ip_address; }
	}
}

my @matches	= sort( grep { m/$search/ } keys(%hosts));

if      ( $#matches     == -1 ) { $title        = $remote_ip = $search; }
elsif	( $#matches	== 0 )
{
	$title		= $matches[0];
	$remote_ip	= $hosts{$title};
}
elsif	( $#matches > 0 )
{
	my $choice	= -1;
	until ( ($choice >= 0) and ( $choice <= $#matches) )
	{
		print_matches(@matches);
		chomp($choice	= <STDIN>);
		unless ( $choice =~ m/^\d+$/ )	{ $choice	= -1; }
	}
	$title		= $matches[$choice];
	$remote_ip	= $hosts{$title};
}

if ( $remote_login )
{
	$remote_ip	= $remote_login . '@' . $remote_ip;
	$title		= $remote_login . '@' . $title;
}

printf("\033]0;$title\007");
exec("ssh -X $remote_ip");

sub	print_matches
{
	my @matches	= @_;
	my $columns	= 3;
	foreach my $element (0..$#matches)
	{
		unless ($element%$columns)	{ printf("\n"); }
		printf("%2d %16s\t", $element, $matches[$element]);
	}
	printf("\n\n Enter # of choice : ");
}
